### ISSUE TITLE
Issues with launching tasks on Mac

### ISSUE THREAD

**Issue by juanfcocontreras** [P403n1x87/austin-vscode#50]
I am running VS Code on MacOS Ventura 13.6.1, with the latest version of the extension (0.16) and `austin` installed from conda-forge. I also have the permissions in the sudoers file. However, I can't get a satisfactory task configuration.

If I set `austin` as a task type, I have two problems:

- it doesn't add `sudo` at the beginning, so I don't have permissions (that should be fixed according to https://github.com/P403n1x87/austin-vscode/commit/38720cf640c47a9ccfaaade63eff724bafbfeef1). As a workaround, I can add myself using the `command` option.
- I don't get variable substitution like `${file}`. This appears in this issue https://github.com/P403n1x87/austin-vscode/issues/35, but since it is closed, I understand that it has been solved. However, it is not working for me.

On the other hand, if I set the task to be of `script` type, although the two previous problems are solved, the results are not integrated in the extension, so they don't appear in the panels.

I am sure I am doing something wrong or have misunderstood how to configure the extension, so I would appreciate information on this.

Thanks in advance.

**Comment by P403n1x87** [comment]
@juanfcocontreras I think you're doing nothing wrong:

> it doesn't add sudo at the beginning

The `sudo` command is added when profiling a Python script in VS Code using the "Profile with Austin" command (triggered with <kbd>shift</kbd> + <kbd>f5</kbd>). When using a task instead, the `sudo` command needs to be specified manually, like you did.

> I don't get variable substitution like ${file}

I believe that issue was marked as resolved because the "Profile with Austin" command was enough to resolve the original issue. Austin tasks don't do variable substitution automatically yet.

So currently there are are two options:
- Use the "Profile with Austin" command, which automatically adds `sudo` to the command.
- Run Austin manually in the terminal and then use the Flame Graph panel to open the collected samples.

I appreciate that it would be handy to have variable substitution in tasks, so I'll try to work on it when I have some time, but contributions are also very welcome 🙂 . Hope this helps for now!

**Comment by juanfcocontreras** [comment]
Understood, I will use Profile with Austin!

 Thank you so much!!
